/*
 * SPDX-License-Identifier: AGPL-3.0-or-later
 * 
 * Copyright (C) 2023 Ministero della Salute
 * 
 * This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
 * 
 * You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>.
 */
package it.finanze.sanita.gva.enums;

import it.finanze.sanita.gva.validator.IUC;
import lombok.AccessLevel;
import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor(access = AccessLevel.PRIVATE)
public enum RADErrorEnum implements IUC{
	ESAME_ESEGUITO_CODE("001"),
	ESAME_ESEGUITO_CODE_SYSTEM("002"),
	ESAME_ESEGUITO_CODE_SYSTEM_NAME("003"),
	ESAME_ESEGUITO_DISPLAY_NAME("004"),
	ESAME_ESEGUITO_MOOD_CODE("005"),
	ESAME_ESEGUITO_CLASS_CODE("006"),
	ESAME_ESEGUITO_EFFECTIVE_TIME("007"),
	
	REFERTO_CODE("008"),
	REFERTO_CODE_SYSTEM("009"),
	REFERTO_CODE_SYSTEM_NAME("010"),
	REFERTO_DISPLAY_NAME("011"),

	CONCLUSIONI_CODE("012"),
	CONCLUSIONI_CODE_SYSTEM("013"),
	CONCLUSIONI_CODE_SYSTEM_NAME("014"),
	CONCLUSIONI_DISPLAY_NAME("015"),
	
	DICOM_CODE("016"),
	DICOM_CODE_SYSTEM("017"),
	DICOM_CODE_SYSTEM_NAME("018"),
	DICOM_DISPLAY_NAME("019"),
	
	QUESITO_CODE("020"),
	QUESITO_CODE_SYSTEM("021"),
	QUESITO_CODE_SYSTEM_NAME("022"),
	QUESITO_DISPLAY_NAME("023"),
	QUESITO_OBS_MOOD_CODE("024"),
	QUESITO_OBS_CLASS_CODE("025"),
	QUESITO_OBS_CODE("026"),
	QUESITO_OBS_CODE_SYSTEM("027"),
	QUESITO_OBS_CODE_SYSTEM_NAME("028"),
	QUESITO_OBS_DISPLAY_NAME("029"),
	QUESITO_OBS_VALUE_CODE_SYSTEM("030"),
	QUESITO_OBS_VALUE_CODE_SYSTEM_NAME("031"),
	
	STORIA_CODE("032"),
	STORIA_CODE_SYSTEM("033"),
	STORIA_CODE_SYSTEM_NAME("034"),
	STORIA_CODE_DISPLAY_NAME("035"),
	STORIA_OBS_MOOD_CODE("036"),
	STORIA_OBS_CLASS_CODE("037"),
	STORIA_OBS_CODE("038"),
	STORIA_OBS_CODE_SYSTEM("039"),
	STORIA_OBS_CODE_SYSTEM_NAME("040"),
	STORIA_OBS_DISPLAY_NAME("041"),
	STORIA_ORG_MOOD_CODE("043"),
	STORIA_ORG_CLASS_CODE("044"),
	STORIA_ORG_CODE("045"),
	STORIA_ORG_CODE_SYSTEM("046"),
	STORIA_ORG_STATUS_CODE("047"),
	STORIA_ORG_REL_CLASS_CODE("048"),
	STORIA_ORG_REL_SUB_GEN("050"),
	STORIA_ORG_OBS_VALUE_TYPE("052"),
	STORIA_ORG_OBS_VALUE_CODE("053"),
	STORIA_ORG_OBS_VALUE_CODE_SYSTEM("054"),
	STORIA_ORG_OBS_VALUE_CODE_SYSTEM_NAME("055"),
	STORIA_ORG_OBS_VALUE_DISPLAY_NAME("056"),
	STORIA_ORG_OBS_CLASS_CODE("057"),
	STORIA_ORG_OBS_MOOD_CODE("058"),
	STORIA_ALLERGIE_CODE("059"),
	STORIA_ALLERGIE_CODE_SYSTEM("060"),
	STORIA_ALLERGIE_CODE_SYSTEM_NAME("061"),
	STORIA_ALLERGIE_CODE_DISPLAY_NAME("062"),
	STORIA_ALLERGIE_ACT_OBS_CODE("065"),
	STORIA_ALLERGIE_ACT_OBS_CODE_SYSTEM("066"),
	STORIA_ALLERGIE_ACT_OBS_DISPLAY_NAME("067"),
	STORIA_ALLERGIE_ACT_OBS_STATUS_CODE("068"),
	STORIA_ALLERGIE_ACT_OBS_VALUE_CODE("069"),
	STORIA_ALLERGIE_ACT_OBS_OBS_CODE("070"),
	STORIA_ALLERGIE_ACT_OBS_OBS_CODE_SYSTEM("071"),
	STORIA_ALLERGIE_ACT_OBS_OBS_CODE_SYSTEM_NAME("072"),
	STORIA_ALLERGIE_ACT_OBS_OBS_DISPLAY_NAME("073"),
	STORIA_ALLERGIE_ACT_OBS_OBS_STATUS_CODE("074"),
	STORIA_ALLERGIE_ACT_OBS_ACT_CODE("075"),
	STORIA_ALLERGIE_ACT_OBS_ACT_CODE_SYSTEM("076"),
	STORIA_ALLERGIE_ACT_OBS_ACT_CODE_SYSTEM_NAME("077"),
	STORIA_ALLERGIE_ACT_OBS_ACT_DISPLAY_NAME("078"),
	STORIA_ALLERGIE_ACT_OBS_ACT_STATUS("079"),

	ESAMI_CODE("080"),
	ESAMI_CODE_SYSTEM("081"),
	ESAMI_CODE_SYSTEM_NAME("082"),
	ESAMI_DISPLAY_NAME("083"),
	ESAMI_OBS_MOOD_CODE("084"),
	ESAMI_OBS_CLASS_CODE("085"),
	ESAMI_OBS_EFF_TIME("086"),
	ESAMI_OBS_EFF_TIME_LOW("087"),
	ESAMI_OBS_EFF_TIME_HIGH("088"),
	
	SUGGERIMENTI_CODE("089"),
	SUGGERIMENTI_CODE_SYSTEM("090"),
	SUGGERIMENTI_CODE_SYSTEM_NAME("091"),
	SUGGERIMENTI_CODE_DISPLAY_NAME("092"),

	INFO_AGG_CODE("093"),
	INFO_AGG_CODE_SYSTEM("094"),
	INFO_AGG_CODE_SYSTEM_NAME("095"),
	INFO_AGG_CODE_DISPLAY_NAME("096");
	
	private String code;

}
