/*
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */
package it.finanze.sanita.gva.enums;

import it.finanze.sanita.gva.validator.IUC;

public enum TRASFErrorEnum implements IUC{

	SECTION_CODE("001"),
	SECTION_CODE_SYSTEM("002"),
	SECTION_CODE_SYSTEM_NAME("003"),
	SECTION_DISPLAY_NAME("004"),
	SECTION_COMPONENT_CODE("005"),
	SECTION_COMPONENT_CODE_SYSTEM("006"),
	SECTION_COMPONENT_CODE_SYSTEM_NAME("007"),
	SECTION_COMPONENT_DISPLAY_NAME("008"),
	SECTION_COMPONENT_TYPE_CODE("009"),
	SECTION_COMPONENT_ACT_MOODE_CODE("010"),
	SECTION_COMPONENT_ACT_CLASS_CODE("011"),
	SECTION_COMPONENT_ACT_STATUS_CODE("012"),
	SECTION_COMPONENT_ACT_SPECIMENROLE_TYPE_CODE("013"),
	SECTION_COMPONENT_ACT_SPECIMENROLE_CLASS_CODE("014"),
	SECTION_COMPONENT_ACT_SPECIMENROLE_CODE("015"),
	SECTION_COMPONENT_ACT_SPECIMENROLE_CODE_SYSTEM("015"),
	SECTION_COMPONENT_ACT_SPECIMENROLE_CODE_SYSTEM_NAME("016"),
	SECTION_COMPONENT_ACT_SPECIMENROLE_DISPLAY_NAME("017"),
	SECTION_COMPONENT_ACT_TYPE_CODE("018"),
	SECTION_COMPONENT_ACT_ORG_CLASS_CODE("019"),
	SECTION_COMPONENT_ACT_ORG_STATUS_CODE("020"),
	SECTION_COMPONENT_ACT_ORG_TYPE_CODE("021"),
	SECTION_COMPONENT_ACT_ORG_CODE("022"),
	SECTION_COMPONENT_ACT_ORG_DISPLAY_NAME("023"),
	SECTION_COMPONENT_ACT_ORG_OBS_STATUS_CODE("024"),
	SECTION_COMPONENT_ACT_ORG_OBS_CODE("025"),
	SECTION_COMPONENT_ACT_ORG_OBS_CODE_SYSTEM("026"),
	SECTION_COMPONENT_ACT_ORG_OBS_CODE_SYSTEM_NAME("027"),
	SECTION_COMPONENT_ACT_ORG_OBS_DISPLAY_NAME("028"),
	SECTION_COMPONENT_ACT_ORG_COMP_TYPE_CODE("029"),
	SECTION_COMPONENT_ACT_ORG_COMP_CODE("030"),
	SECTION_COMPONENT_ACT_ORG_COMP_CODE_SYSYTEM("031"),
	SECTION_COMPONENT_ACT_ORG_COMP_CODE_SYSTEM_NAME("032"),
	SECTION_COMPONENT_ACT_ORG_COMP_DISPLAY_NAME("033"),
	SECTION_COMPONENT_ACT_ORG_COMP_STATUS_CODE("034"),
	SECTION_COMPONENT_ACT_ORG_COMP_OBS_CODE("035"),
	SECTION_COMPONENT_ACT_ORG_COMP_OBS_CODE_SYSTEM("036"),
	SECTION_COMPONENT_ACT_ORG_COMP_OBS_CODE_SYSTEM_NAME("037"),
	SECTION_COMPONENT_ACT_ORG_COMP_OBS_DISPLAY_NAME("038"),
	SECTION_COMPONENT_ACT_ORG_COMP_OBS_STATUS_CODE("039"),
	SECTION_COMPONENT_ACT_ER_TYPEC_ODE("040"),
	SECTION_COMPONENT_ACT_ER_CLASS_CODE("041"),
	SECTION_COMPONENT_ACT_ER_MOOD_CODE("042"),
	SECTION_COMPONENT_ACT_ER_CODE("043"),
	SECTION_COMPONENT_ACT_ER_CODE_SYSTEM("044"),
	SECTION_COMPONENT_ACT_ER_CODE_SYSTEM_NAME("045"),
	SECTION_COMPONENT_ACT_ER_DISPLAY_NAME("046"),
	SECTION_COMPONENT_ACT_ORG_CODE_SYSTEM("047"),
	SECTION_COMPONENT_ACT_ORG_CODE_SYSTEM_NAME("048"),
	
	UC00_TRASF0("UC00"),
	UC00_TRASF1("UC01"),
	UC00_TRASF2("UC02"),
	UC00_TRASF3("UC03"),
	UC00_TRASF4("UC04"),
	UC00_TRASF5("UC05"),
	UC00_TRASF6("UC06"),
	UC00_TRASF7("UC07"),
	UC00_TRASF8("UC08"),
	UC00_TRASF9("UC09"),
	UC00_TRASF10("UC10"),
	UC00_TRASF11("UC11"),
	UC00_TRASF12("UC12"),
	UC00_TRASF13("UC13"),
	UC00_TRASF14("UC14"),
	UC00_TRASF15("UC15"),
	UC00_TRASF16("UC16"),
	UC00_TRASF17("UC17"),
	UC00_TRASF18("UC18"),
	UC00_TRASF19("UC19"),
	UC00_TRASF20("UC20"),
	UC00_TRASF21("UC21"),
	UC00_TRASF22("UC22"),
	UC00_TRASF23("UC23"),
	UC00_TRASF24("UC24"),
	UC00_TRASF25("UC25"),
	UC00_TRASF26("UC26"),
	UC00_TRASF27("UC27"),
	UC00_TRASF28("UC28"),
	UC00_TRASF29("UC29"),
	UC00_TRASF30("UC30"),
	UC00_TRASF31("UC31");
	
	private String code;
	
	private TRASFErrorEnum(String inCode) {
		code = inCode;
	}
	
	public String getCode() {
		return code;
	}

}
