name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build jwt-generator with Maven
        working-directory: ./jwt-generator
        run: mvn --batch-mode --update-snapshots package
      - name: Build pdf-generator with Maven
        working-directory: ./pdf-generator
        run: mvn --batch-mode --update-snapshots package
      - run: mkdir staging && cp {jwt-generator,pdf-generator}target/*.jar staging
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
        
