name: Java Build
on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: Build jwt-generator with Maven
        working-directory: ./jwt-generator
        run: mvn --batch-mode --update-snapshots package
      - name: Build pdf-generator with Maven
        working-directory: ./pdf-generator
        run: mvn --batch-mode --update-snapshots package
      - name: collecting jars
        run: mkdir staging && cp {jwt-generator,pdf-generator}/target/*.jar staging
      - name: create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "staging/*.jar"
          tag: "latest"
          commit: "main"
          allowUpdates: true
         
          
